[project]
name = "just-like-me"
version = "0.2.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "zhengfeng", email = "zhengfeng.cai@thoughtworks.com" }
]
requires-python = ">=3.12"
dependencies = [
    "hindsight-client>=0.9.1",
]

[project.scripts]
"just_like_me.load_memory" = "just_like_me.load_memory:main"
"just_like_me.daemon.install" = "just_like_me.daemon:install"
"just_like_me.daemon.uninstall" = "just_like_me.daemon:uninstall"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
source-exclude = ["src/just_like_me/test_*.py"]
